"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var vue_1 = require("vue");
var pinia_1 = require("pinia");
var MainLayout_vue_1 = require("@app/layouts/MainLayout.vue");
var router_1 = require("@app/router");
var app = (0, vue_1.createApp)(MainLayout_vue_1.default);
app.use((0, pinia_1.createPinia)());
app.use(router_1.default);
app.mount('#app');
